; Configuration file for dide_mod.

[General]
EnableMod=1
EnableLogging=0
;LogFile=dide_mod.log

; Toggle features
; 1 = enable; 0 = disable
[Features]
DeveloperMenu=1
CustomPak=1

; Custom .pak files to load
; Enable with "1" or "enabled=1"; disable with "0" or "enabled=0".
; Optionally specify a stage to load at using "some.pak=[...],stage=<stage name>".
; ┌────────────┬────────────────────────────┬─────────────────┐
; │ stage      │ description                │ supported games │
; ├────────────┼────────────────────────────┼─────────────────┤
; │ after_main │ after main paks (default)  │ all             │
; │ after_dlc  │ after DLCs                 │ DI(R)           │
; └────────────┴────────────────────────────┴─────────────────┘
[CustomPak]
;path\to\enabled\data.pak=1
;path\to\disabled\data.pak=0
;some.pak=enabled=1,stage=after_dlc
